//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webTesteApi.svcintranet {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://drhunet.edunet.sp.gov.br/Servicos/Autenticacao", ConfigurationName="svcintranet.wsAutenticacaoSoap")]
    public interface wsAutenticacaoSoap {
        
        // CODEGEN: Generating message contract since element name ObterChavePublicaResult from namespace http://drhunet.edunet.sp.gov.br/Servicos/Autenticacao is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://drhunet.edunet.sp.gov.br/Servicos/Autenticacao/ObterChavePublica", ReplyAction="*")]
        webTesteApi.svcintranet.ObterChavePublicaResponse ObterChavePublica(webTesteApi.svcintranet.ObterChavePublicaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://drhunet.edunet.sp.gov.br/Servicos/Autenticacao/ObterChavePublica", ReplyAction="*")]
        System.Threading.Tasks.Task<webTesteApi.svcintranet.ObterChavePublicaResponse> ObterChavePublicaAsync(webTesteApi.svcintranet.ObterChavePublicaRequest request);
        
        // CODEGEN: Generating message contract since element name Mensagem from namespace http://drhunet.edunet.sp.gov.br/Servicos/Autenticacao is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://drhunet.edunet.sp.gov.br/Servicos/Autenticacao/ObterPermissoesUsuario", ReplyAction="*")]
        webTesteApi.svcintranet.ObterPermissoesUsuarioResponse ObterPermissoesUsuario(webTesteApi.svcintranet.ObterPermissoesUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://drhunet.edunet.sp.gov.br/Servicos/Autenticacao/ObterPermissoesUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<webTesteApi.svcintranet.ObterPermissoesUsuarioResponse> ObterPermissoesUsuarioAsync(webTesteApi.svcintranet.ObterPermissoesUsuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterChavePublicaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterChavePublica", Namespace="http://drhunet.edunet.sp.gov.br/Servicos/Autenticacao", Order=0)]
        public webTesteApi.svcintranet.ObterChavePublicaRequestBody Body;
        
        public ObterChavePublicaRequest() {
        }
        
        public ObterChavePublicaRequest(webTesteApi.svcintranet.ObterChavePublicaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObterChavePublicaRequestBody {
        
        public ObterChavePublicaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterChavePublicaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterChavePublicaResponse", Namespace="http://drhunet.edunet.sp.gov.br/Servicos/Autenticacao", Order=0)]
        public webTesteApi.svcintranet.ObterChavePublicaResponseBody Body;
        
        public ObterChavePublicaResponse() {
        }
        
        public ObterChavePublicaResponse(webTesteApi.svcintranet.ObterChavePublicaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://drhunet.edunet.sp.gov.br/Servicos/Autenticacao")]
    public partial class ObterChavePublicaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObterChavePublicaResult;
        
        public ObterChavePublicaResponseBody() {
        }
        
        public ObterChavePublicaResponseBody(string ObterChavePublicaResult) {
            this.ObterChavePublicaResult = ObterChavePublicaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterPermissoesUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterPermissoesUsuario", Namespace="http://drhunet.edunet.sp.gov.br/Servicos/Autenticacao", Order=0)]
        public webTesteApi.svcintranet.ObterPermissoesUsuarioRequestBody Body;
        
        public ObterPermissoesUsuarioRequest() {
        }
        
        public ObterPermissoesUsuarioRequest(webTesteApi.svcintranet.ObterPermissoesUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://drhunet.edunet.sp.gov.br/Servicos/Autenticacao")]
    public partial class ObterPermissoesUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Mensagem;
        
        public ObterPermissoesUsuarioRequestBody() {
        }
        
        public ObterPermissoesUsuarioRequestBody(string Mensagem) {
            this.Mensagem = Mensagem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterPermissoesUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterPermissoesUsuarioResponse", Namespace="http://drhunet.edunet.sp.gov.br/Servicos/Autenticacao", Order=0)]
        public webTesteApi.svcintranet.ObterPermissoesUsuarioResponseBody Body;
        
        public ObterPermissoesUsuarioResponse() {
        }
        
        public ObterPermissoesUsuarioResponse(webTesteApi.svcintranet.ObterPermissoesUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://drhunet.edunet.sp.gov.br/Servicos/Autenticacao")]
    public partial class ObterPermissoesUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObterPermissoesUsuarioResult;
        
        public ObterPermissoesUsuarioResponseBody() {
        }
        
        public ObterPermissoesUsuarioResponseBody(string ObterPermissoesUsuarioResult) {
            this.ObterPermissoesUsuarioResult = ObterPermissoesUsuarioResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsAutenticacaoSoapChannel : webTesteApi.svcintranet.wsAutenticacaoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsAutenticacaoSoapClient : System.ServiceModel.ClientBase<webTesteApi.svcintranet.wsAutenticacaoSoap>, webTesteApi.svcintranet.wsAutenticacaoSoap {
        
        public wsAutenticacaoSoapClient() {
        }
        
        public wsAutenticacaoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsAutenticacaoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsAutenticacaoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsAutenticacaoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webTesteApi.svcintranet.ObterChavePublicaResponse webTesteApi.svcintranet.wsAutenticacaoSoap.ObterChavePublica(webTesteApi.svcintranet.ObterChavePublicaRequest request) {
            return base.Channel.ObterChavePublica(request);
        }
        
        public string ObterChavePublica() {
            webTesteApi.svcintranet.ObterChavePublicaRequest inValue = new webTesteApi.svcintranet.ObterChavePublicaRequest();
            inValue.Body = new webTesteApi.svcintranet.ObterChavePublicaRequestBody();
            webTesteApi.svcintranet.ObterChavePublicaResponse retVal = ((webTesteApi.svcintranet.wsAutenticacaoSoap)(this)).ObterChavePublica(inValue);
            return retVal.Body.ObterChavePublicaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webTesteApi.svcintranet.ObterChavePublicaResponse> webTesteApi.svcintranet.wsAutenticacaoSoap.ObterChavePublicaAsync(webTesteApi.svcintranet.ObterChavePublicaRequest request) {
            return base.Channel.ObterChavePublicaAsync(request);
        }
        
        public System.Threading.Tasks.Task<webTesteApi.svcintranet.ObterChavePublicaResponse> ObterChavePublicaAsync() {
            webTesteApi.svcintranet.ObterChavePublicaRequest inValue = new webTesteApi.svcintranet.ObterChavePublicaRequest();
            inValue.Body = new webTesteApi.svcintranet.ObterChavePublicaRequestBody();
            return ((webTesteApi.svcintranet.wsAutenticacaoSoap)(this)).ObterChavePublicaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webTesteApi.svcintranet.ObterPermissoesUsuarioResponse webTesteApi.svcintranet.wsAutenticacaoSoap.ObterPermissoesUsuario(webTesteApi.svcintranet.ObterPermissoesUsuarioRequest request) {
            return base.Channel.ObterPermissoesUsuario(request);
        }
        
        public string ObterPermissoesUsuario(string Mensagem) {
            webTesteApi.svcintranet.ObterPermissoesUsuarioRequest inValue = new webTesteApi.svcintranet.ObterPermissoesUsuarioRequest();
            inValue.Body = new webTesteApi.svcintranet.ObterPermissoesUsuarioRequestBody();
            inValue.Body.Mensagem = Mensagem;
            webTesteApi.svcintranet.ObterPermissoesUsuarioResponse retVal = ((webTesteApi.svcintranet.wsAutenticacaoSoap)(this)).ObterPermissoesUsuario(inValue);
            return retVal.Body.ObterPermissoesUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webTesteApi.svcintranet.ObterPermissoesUsuarioResponse> webTesteApi.svcintranet.wsAutenticacaoSoap.ObterPermissoesUsuarioAsync(webTesteApi.svcintranet.ObterPermissoesUsuarioRequest request) {
            return base.Channel.ObterPermissoesUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<webTesteApi.svcintranet.ObterPermissoesUsuarioResponse> ObterPermissoesUsuarioAsync(string Mensagem) {
            webTesteApi.svcintranet.ObterPermissoesUsuarioRequest inValue = new webTesteApi.svcintranet.ObterPermissoesUsuarioRequest();
            inValue.Body = new webTesteApi.svcintranet.ObterPermissoesUsuarioRequestBody();
            inValue.Body.Mensagem = Mensagem;
            return ((webTesteApi.svcintranet.wsAutenticacaoSoap)(this)).ObterPermissoesUsuarioAsync(inValue);
        }
    }
}
